# Dockerfile
FROM pytorch/pytorch:2.3.1-cuda11.8-cudnn8-devel

# 必要なパッケージのインストール
RUN apt-get update && \
    apt-get install -y openssh-server python3 python3-pip git iputils-ping net-tools nmon curl
